# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e0bdc46293b141eca577d2d1eaed2480dc69747b13227e6084718f839754d88a2f6a90b4314208ba8f4816ddbf1c8f67e61db451509b99cc258bb64b90b332a9

test:
  secret_key_base: fceb3715bbf2aba55441fce113b8ea0bf925580e9f79ed2dcd19e86e407703a793e39309f8952404a5fe3110e8f688a3edf3fa6159b3b1c457d052b6eed33be0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
